package com.app.journeyjoy.dto;

public class CashfreePaymentResponse {

	    private String orderId; // The unique order ID generated by Cashfree
	    private String paymentStatus; // Status of the payment (e.g., SUCCESS, FAILED)
	    private String paymentMessage; // A message regarding the payment status
	    private String paymentMode; // Payment mode (e.g., Credit Card, Net Banking)
	    private String transactionId; // The transaction ID from Cashfree
	    private String signature; // A security signature to verify the response

	    // Getters and Setters

	    public String getOrderId() {
	        return orderId;
	    }

	    public void setOrderId(String orderId) {
	        this.orderId = orderId;
	    }

	    public String getPaymentStatus() {
	        return paymentStatus;
	    }

	    public void setPaymentStatus(String paymentStatus) {
	        this.paymentStatus = paymentStatus;
	    }

	    public String getPaymentMessage() {
	        return paymentMessage;
	    }

	    public void setPaymentMessage(String paymentMessage) {
	        this.paymentMessage = paymentMessage;
	    }

	    public String getPaymentMode() {
	        return paymentMode;
	    }

	    public void setPaymentMode(String paymentMode) {
	        this.paymentMode = paymentMode;
	    }

	    public String getTransactionId() {
	        return transactionId;
	    }

	    public void setTransactionId(String transactionId) {
	        this.transactionId = transactionId;
	    }

	    public String getSignature() {
	        return signature;
	    }

	    public void setSignature(String signature) {
	        this.signature = signature;
	    }
	

}
